#!/bin/env bash
bash /root/jd/jd.sh jd_bean_change now
bash /root/jd/jd.sh jd_bean_home now
bash /root/jd/jd.sh jd_bean_sign now
bash /root/jd/jd.sh jd_beauty now
bash /root/jd/jd.sh jd_blueCoin now
bash /root/jd/jd.sh jd_bookshop now
bash /root/jd/jd.sh jd_car_exchange now
bash /root/jd/jd.sh jd_car now
bash /root/jd/jd.sh jd_cash now
bash /root/jd/jd.sh jd_cfd now
bash /root/jd/jd.sh jd_club_lottery now
bash /root/jd/jd.sh jd_crazy_joy_bonus now
bash /root/jd/jd.sh jd_crazy_joy now
bash /root/jd/jd.sh jd_daily_egg now
bash /root/jd/jd.sh jd_dreamFactory now
bash /root/jd/jd.sh jd_entertainment now
bash /root/jd/jd.sh jd_factory_component now
bash /root/jd/jd.sh jd_fruit now
bash /root/jd/jd.sh jd_get_share_code now
bash /root/jd/jd.sh jd_global now
bash /root/jd/jd.sh jd_global_mh now
bash /root/jd/jd.sh jd_jdaxc now
bash /root/jd/jd.sh jd_jdfactory now
bash /root/jd/jd.sh jd_jdzz now
bash /root/jd/jd.sh jd_joy_feedPets now
bash /root/jd/jd.sh jd_joy_help now
bash /root/jd/jd.sh jd_joy now
bash /root/jd/jd.sh jd_joy_reward now
bash /root/jd/jd.sh jd_joy_run now
bash /root/jd/jd.sh jd_jxd now
bash /root/jd/jd.sh jd_jxnc now
bash /root/jd/jd.sh jd_kd now
bash /root/jd/jd.sh jd_lenovo now
bash /root/jd/jd.sh jd_live now
bash /root/jd/jd.sh jd_live_redrain now
bash /root/jd/jd.sh jd_lotteryMachine now
bash /root/jd/jd.sh jd_marketLottery now
bash /root/jd/jd.sh jd_mgold now
bash /root/jd/jd.sh jd_mohe now
bash /root/jd/jd.sh jd_moneyTree now
bash /root/jd/jd.sh jd_mother_jump now
bash /root/jd/jd.sh jd_ms now
bash /root/jd/jd.sh jd_necklace now
bash /root/jd/jd.sh jd_nzmh now
bash /root/jd/jd.sh jd_oneplus now
bash /root/jd/jd.sh jd_paopao now
bash /root/jd/jd.sh jd_pet now
bash /root/jd/jd.sh jd_pigPet now
bash /root/jd/jd.sh jd_plantBean now
bash /root/jd/jd.sh jd_price now
bash /root/jd/jd.sh jd_rankingList now
bash /root/jd/jd.sh jd_redPacket now
bash /root/jd/jd.sh jd_sgmh now
bash /root/jd/jd.sh jd_shake now
bash /root/jd/jd.sh jd_shop now
bash /root/jd/jd.sh jd_small_home now
bash /root/jd/jd.sh jd_speed now
bash /root/jd/jd.sh jd_speed_redpocke now
bash /root/jd/jd.sh jd_speed_sign now
bash /root/jd/jd.sh jd_superDay now
bash /root/jd/jd.sh jd_superMarket now
bash /root/jd/jd.sh jd_syj now
bash /root/jd/jd.sh jd_unsubscribe now
bash /root/jd/jd.sh jd_verify now
bash /root/jd/jd.sh jd_wish now
bash /root/jd/jd.sh jd_xmf now
bash /root/jd/jd.sh jd_xxl_gh now
bash /root/jd/jd.sh jx_sign now
bash /root/jd/jd.sh jd_crazy_joy_coin now
